### ISSUE TITLE
doesn twork

### ISSUE THREAD

**Issue by Hue-Jhan** [KasRoudra/nasahack#1]
: (

it doesnr hack nasa!
clickbait!!!

**Comment by KasRoudra** [comment]
@Hue-Jhan 
1. I am not asking anyone to use it
2. It's not harming anyone
3. It's just uploaded to my personal account

So it's okay to be as it is

**Comment by Hue-Jhan** [comment]
> @Hue-Jhan 
> 1. I am not asking anyone to use it
> 2. It's not harming anyone
> 3. It's just uploaded to my personal account
> 
> So it's okay to be as it is

Dude it was obviously a joke
